(cl:defpackage serverpkg-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "NONETYPE"
   "<NONETYPE-REQUEST>"
   "NONETYPE-REQUEST"
   "<NONETYPE-RESPONSE>"
   "NONETYPE-RESPONSE"
  ))

