// Generated by gencpp from file serverpkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVERPKG_MESSAGE_ADDTWOINTS_H
#define SERVERPKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <serverpkg/AddTwoIntsRequest.h>
#include <serverpkg/AddTwoIntsResponse.h>


namespace serverpkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace serverpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serverpkg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::serverpkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::serverpkg::AddTwoInts > {
  static const char* value()
  {
    return "serverpkg/AddTwoInts";
  }

  static const char* value(const ::serverpkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::serverpkg::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::serverpkg::AddTwoInts >
template<>
struct MD5Sum< ::serverpkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serverpkg::AddTwoInts >::value();
  }
  static const char* value(const ::serverpkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverpkg::AddTwoIntsRequest> should match
// service_traits::DataType< ::serverpkg::AddTwoInts >
template<>
struct DataType< ::serverpkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::serverpkg::AddTwoInts >::value();
  }
  static const char* value(const ::serverpkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serverpkg::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::serverpkg::AddTwoInts >
template<>
struct MD5Sum< ::serverpkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serverpkg::AddTwoInts >::value();
  }
  static const char* value(const ::serverpkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverpkg::AddTwoIntsResponse> should match
// service_traits::DataType< ::serverpkg::AddTwoInts >
template<>
struct DataType< ::serverpkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::serverpkg::AddTwoInts >::value();
  }
  static const char* value(const ::serverpkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVERPKG_MESSAGE_ADDTWOINTS_H
