// Generated by gencpp from file serverpkg/NoneTypeResponse.msg
// DO NOT EDIT!


#ifndef SERVERPKG_MESSAGE_NONETYPERESPONSE_H
#define SERVERPKG_MESSAGE_NONETYPERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serverpkg
{
template <class ContainerAllocator>
struct NoneTypeResponse_
{
  typedef NoneTypeResponse_<ContainerAllocator> Type;

  NoneTypeResponse_()
    {
    }
  NoneTypeResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::serverpkg::NoneTypeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serverpkg::NoneTypeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NoneTypeResponse_

typedef ::serverpkg::NoneTypeResponse_<std::allocator<void> > NoneTypeResponse;

typedef boost::shared_ptr< ::serverpkg::NoneTypeResponse > NoneTypeResponsePtr;
typedef boost::shared_ptr< ::serverpkg::NoneTypeResponse const> NoneTypeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serverpkg::NoneTypeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace serverpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serverpkg::NoneTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serverpkg::NoneTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serverpkg::NoneTypeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::serverpkg::NoneTypeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serverpkg/NoneTypeResponse";
  }

  static const char* value(const ::serverpkg::NoneTypeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::serverpkg::NoneTypeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NoneTypeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serverpkg::NoneTypeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::serverpkg::NoneTypeResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SERVERPKG_MESSAGE_NONETYPERESPONSE_H
