// Generated by gencpp from file serverpkg/NoneType.msg
// DO NOT EDIT!


#ifndef SERVERPKG_MESSAGE_NONETYPE_H
#define SERVERPKG_MESSAGE_NONETYPE_H

#include <ros/service_traits.h>


#include <serverpkg/NoneTypeRequest.h>
#include <serverpkg/NoneTypeResponse.h>


namespace serverpkg
{

struct NoneType
{

typedef NoneTypeRequest Request;
typedef NoneTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NoneType
} // namespace serverpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serverpkg::NoneType > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::serverpkg::NoneType&) { return value(); }
};

template<>
struct DataType< ::serverpkg::NoneType > {
  static const char* value()
  {
    return "serverpkg/NoneType";
  }

  static const char* value(const ::serverpkg::NoneType&) { return value(); }
};


// service_traits::MD5Sum< ::serverpkg::NoneTypeRequest> should match
// service_traits::MD5Sum< ::serverpkg::NoneType >
template<>
struct MD5Sum< ::serverpkg::NoneTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serverpkg::NoneType >::value();
  }
  static const char* value(const ::serverpkg::NoneTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverpkg::NoneTypeRequest> should match
// service_traits::DataType< ::serverpkg::NoneType >
template<>
struct DataType< ::serverpkg::NoneTypeRequest>
{
  static const char* value()
  {
    return DataType< ::serverpkg::NoneType >::value();
  }
  static const char* value(const ::serverpkg::NoneTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serverpkg::NoneTypeResponse> should match
// service_traits::MD5Sum< ::serverpkg::NoneType >
template<>
struct MD5Sum< ::serverpkg::NoneTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serverpkg::NoneType >::value();
  }
  static const char* value(const ::serverpkg::NoneTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverpkg::NoneTypeResponse> should match
// service_traits::DataType< ::serverpkg::NoneType >
template<>
struct DataType< ::serverpkg::NoneTypeResponse>
{
  static const char* value()
  {
    return DataType< ::serverpkg::NoneType >::value();
  }
  static const char* value(const ::serverpkg::NoneTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVERPKG_MESSAGE_NONETYPE_H
