// Generated by gencpp from file ros_tut/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_TUT_MESSAGE_ADDTWOINTS_H
#define ROS_TUT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_tut/AddTwoIntsRequest.h>
#include <ros_tut/AddTwoIntsResponse.h>


namespace ros_tut
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_tut


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tut::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_tut::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_tut::AddTwoInts > {
  static const char* value()
  {
    return "ros_tut/AddTwoInts";
  }

  static const char* value(const ::ros_tut::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tut::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_tut::AddTwoInts >
template<>
struct MD5Sum< ::ros_tut::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tut::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tut::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tut::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_tut::AddTwoInts >
template<>
struct DataType< ::ros_tut::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tut::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tut::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tut::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_tut::AddTwoInts >
template<>
struct MD5Sum< ::ros_tut::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tut::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tut::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tut::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_tut::AddTwoInts >
template<>
struct DataType< ::ros_tut::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tut::AddTwoInts >::value();
  }
  static const char* value(const ::ros_tut::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TUT_MESSAGE_ADDTWOINTS_H
